---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизоваться на сайте
  - Пользователь должен иметь возможность сыграть в пробную игру без регистрации на сайте
  - Пользователь должен иметь возможность создать новую игру с другим пользователем, с другом или с ботом
  - Пользователь должен иметь возможность создания турниров
  - Пользователь должен иметь возможность выбрать игру по уровню сложности
  - Пользователь должен иметь возможность видеть код своего соперника в режиме онлайн
  - Пользователь должен иметь возможность сдаться и завершить игру в любой момент
  - Пользователь должен иметь возможность просматривать свой рейтинг и рейтинг других пользователей
  - Пользователь должен иметь возможность пригласить друга в игру
  - Пользователь должен иметь возможность выбрать язык кода после создания новой игры
  - Пользователь должен иметь возможность редактировать свой профиль
  - Пользователь должен иметь возможность отправлять сообщения в чат с зарегистрированными пользователями
  - Пользователь должен иметь возможность остановить и возобновить игру в любой момент
  - Пользователь должен иметь возможность выбрать игру по названию и по тегу
  - Пользователь должен иметь возможность просматривать статистику своих игр
non-functional:
  - Cайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Сайт должен соответствовать законам и нормативным актам страны
  - На сайта должна быть форма для ввода данных пользователя
  - Сайт должен выдерживать не менее 1000 одновременных пользователей
